-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 00:01:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onsamu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onsamu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onsamu` DEFAULT CHARACTER SET utf8 ;
USE `onsamu` ;

-- -----------------------------------------------------
-- Table `onsamu`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `remember_token` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `pdf` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`cursos_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`cursos_has_users` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_cursos_cursos1_idx` (`cursos_id` ASC),
  INDEX `fk_users_has_cursos_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_cursos_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `onsamu`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `onsamu`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`video_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`video_cursos` (
  `id` INT NOT NULL,
  `link_video` VARCHAR(150) NULL,
  `cursos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_video_cursos_cursos1_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_video_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `onsamu`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`img_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`img_cursos` (
  `id` INT NOT NULL,
  `link_img` VARCHAR(150) NULL,
  `cursos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_img_cursos_cursos1_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_img_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `onsamu`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`feedback` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `texto` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `update_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`noticias` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `texto` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`img_noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`img_noticias` (
  `id` INT NOT NULL,
  `link_img` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `noticias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_img_noticias_noticias1_idx` (`noticias_id` ASC),
  CONSTRAINT `fk_img_noticias_noticias1`
    FOREIGN KEY (`noticias_id`)
    REFERENCES `onsamu`.`noticias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE=NULL;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS=NULL;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS=NULL;
