-- MySQL Script generated by MySQL Workbench
-- 05/14/18 15:14:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onsamu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onsamu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onsamu` DEFAULT CHARACTER SET utf8 ;
USE `onsamu` ;

-- -----------------------------------------------------
-- Table `onsamu`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` MEDIUMTEXT NULL,
  `img` VARCHAR(150) NULL,
  `pdf` VARCHAR(150) NULL,
  `video1` VARCHAR(150) NULL,
  `video2` VARCHAR(150) NULL,
  `video3` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`cursos_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`cursos_has_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cursos_id` INT NULL,
  `users_id` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_has_users1_users1_idx` (`users_id` ASC),
  INDEX `fk_cursos_has_users1_cursos_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_cursos_has_users1_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `onsamu`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_users1_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `onsamu`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(150) NULL,
  `email` VARCHAR(75) NULL,
  `remember_token` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `onsamu`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `texto` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `update_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`noticias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo_noticia` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `imagem1` VARCHAR(150) NULL DEFAULT NULL,
  `imagem2` VARCHAR(150) NULL DEFAULT NULL,
  `imagem3` VARCHAR(150) NULL DEFAULT NULL,
  `paragrafo1` LONGTEXT NULL DEFAULT NULL,
  `paragrafo2` LONGTEXT NULL,
  `paragrafo3` LONGTEXT NULL,
  `paragrafo4` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onsamu`.`primeiros_socorros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onsamu`.`primeiros_socorros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` LONGTEXT NULL,
  `img` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



INSERT INTO `onsamu`.`users` (`id`, `name`, `password`, `email`, `created_at`, `updated_at`) VALUES ('1', 'samu', '$2y$10$D8VVa8Gu.NBiOCkArbSx4OB91.CJXPxiC4iF38m2hEcUj/FmHRsZS', 'admin@samu.com', '2018-04-19 16:34:39', '2018-04-19 16:34:39');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





